### ISSUE TITLE
about the 802.11ac support

### ISSUE THREAD

**Issue by arnoldzy** [br101/horst#4]
thanks for your great work，i am now using this tool. my question is "when will this tool support the 802.11ac?".because more and more 802.11ac ap in use

**Comment by br101** [comment]
I don't know. It depends on when I first get 802.11ac equipment or someone is willing to fund the work on this...

**Comment by arnoldzy** [comment]
Sure.I can.I would like to donate this project.How to donate,how much?could you give me a specific schedule?

**Comment by br101** [comment]
Happy to hear that! Feel free to donate per PayPal to br1@einfach.org, or contact me on this email address if you want to make other arrangements. Thanks!

**Comment by br101** [comment]
I added 802.11ac support and display of 802.11n or 802.11ac and channel widths recently. Also I verified horst works on ath10k interfaces, and added a option -a to horst because the driver is a bit picky when it comes to monitor mode (this is a driver bug and unrelated to horst). horst version 5.0 will be ready for this century ;)
